const charactersData = [
  { name: "albedo", element: "Geo", rarity: 5, nation: "Mondstadt" },
  { name: "aloy", element: "Cryo", rarity: 5, nation: "Mondstadt" },
  { name: "amber", element: "Pyro", rarity: 4, nation: "Mondstadt" },
  { name: "arataki-itto", element: "Geo", rarity: 5, nation: "Inazuma" },
  { name: "ayaka", element: "Cryo", rarity: 5, nation: "Inazuma" },
  { name: "ayato", element: "Hydro", rarity: 5, nation: "Inazuma" },
  { name: "barbara", element: "Hydro", rarity: 4, nation: "Mondstadt" },
  { name: "beidou", element: "Electro", rarity: 4, nation: "Liyue" },
  { name: "bennett", element: "Pyro", rarity: 4, nation: "Mondstadt" },
  { name: "chongyun", element: "Cryo", rarity: 4, nation: "Liyue" },
  { name: "diluc", element: "Pyro", rarity: 5, nation: "Mondstadt" },
  { name: "diona", element: "Cryo", rarity: 4, nation: "Mondstadt" },
  { name: "eula", element: "Cryo", rarity: 5, nation: "Mondstadt" },
  { name: "fischl", element: "Electro", rarity: 4, nation: "Mondstadt" },
  { name: "ganyu", element: "Cryo", rarity: 5, nation: "Liyue" },
  { name: "gorou", element: "Geo", rarity: 4, nation: "Inazuma" },
  { name: "hu-tao", element: "Pyro", rarity: 5, nation: "Liyue" },
  { name: "jean", element: "Anemo", rarity: 5, nation: "Mondstadt" },
  { name: "kaeya", element: "Cryo", rarity: 4, nation: "Mondstadt" },
  { name: "kazuha", element: "Anemo", rarity: 5, nation: "Inazuma" },
  { name: "keqing", element: "Electro", rarity: 5, nation: "Liyue" },
  { name: "klee", element: "Pyro", rarity: 5, nation: "Mondstadt" },
  { name: "kokomi", element: "Hydro", rarity: 5, nation: "Inazuma" },
  { name: "lisa", element: "Electro", rarity: 4, nation: "Mondstadt" },
  { name: "mona", element: "Hydro", rarity: 54, nation: "Mondstadt" },
  { name: "ningguang", element: "Geo", rarity: 4, nation: "Liyue" },
  { name: "noelle", element: "Geo", rarity: 4, nation: "Mondstadt" },
  { name: "qiqi", element: "Cryo", rarity: 5, nation: "Liyue" },
  { name: "raiden", element: "Electro", rarity: 5, nation: "Inazuma" },
  { name: "razor", element: "Electro", rarity: 4, nation: "Mondstadt" },
  { name: "rosaria", element: "Cryo", rarity: 4, nation: "Mondstadt" },
  { name: "sara", element: "Electro", rarity: 4, nation: "Inazuma" },
  { name: "sayu", element: "Anemo", rarity: 4, nation: "Inazuma" },
  { name: "shenhe", element: "Cryo", rarity: 5, nation: "Liyue" },
  { name: "sucrose", element: "Anemo", rarity: 4, nation: "Mondstadt" },
  { name: "tartaglia", element: "Hydro", rarity: 5, nation: "Liyue" },
  { name: "thoma", element: "Pyro", rarity: 4, nation: "Inazuma" },
  { name: "venti", element: "Anemo", rarity: 5, nation: "Mondstadt" },
  { name: "xiangling", element: "Pyro", rarity: 4, nation: "Liyue" },
  { name: "xiao", element: "Anemo", rarity: 5, nation: "Liyue" },
  { name: "xingqiu", element: "Hydro", rarity: 4, nation: "Liyue" },
  { name: "xinyan", element: "Pyro", rarity: 4, nation: "Liyue" },
  { name: "yae-miko", element: "Electro", rarity: 5, nation: "Inazuma" },
  { name: "yanfei", element: "Pyro", rarity: 4, nation: "Liyue" },
  { name: "yelan", element: "Hydro", rarity: 5, nation: "Liyue" },
  { name: "yoimiya", element: "Pyro", rarity: 5, nation: "Inazuma" },
  { name: "yun-jin", element: "Geo", rarity: 4, nation: "Liyue" },
  { name: "zhongli", element: "Geo", rarity: 5, nation: "Liyue" },

  // Add more character data here...
];

export default charactersData;
